<a href="https://colab.research.google.com/github/plasmatica01/NLP-with-Pytorch/blob/main/02-02b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PyTorch tensor**

A tensor is a data structure or data container we use in PyTorch for carrying arrays of numbers.

**a. Creating a tensor**

In [1]:
pip install torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
  Using cached nvidia_nvjitlink_cu12-12.4.127-py3-none-m

In [2]:
import torch
import numpy as np

In [4]:
# Construct a tensor from an array
array = [[1, 2], [7, 4], [5, 6]]
tensor0 = torch.tensor(array)
print(tensor0)
print("The data structure type of tensor0: ", type(tensor0))
print("The data type of tensor0: ", tensor0.dtype)
print("The shape of tensor0: ", tensor0.shape)

tensor([[1, 2],
        [7, 4],
        [5, 6]])
The data structure type of tensor0:  <class 'torch.Tensor'>
The data type of tensor0:  torch.int64
The shape of tensor0:  torch.Size([3, 2])


In [5]:
# Construct a tensor from a numpy array
np_array = np.array([[1, 2], [7, 4], [5, 6]])
tensor1 = torch.tensor(np_array)
print(tensor1)

tensor([[1, 2],
        [7, 4],
        [5, 6]])


**b. Common Methods: Slicing and Concatenation**

*Slicing*

In [6]:
tensorA = torch.tensor([[1, 1, 1], [2, 2, 2]])
tensorB = torch.tensor([[3, 3, 3], [4, 4, 4]])

In [9]:
# Slicing is all the same as numpy arrays
print('Slicing the first two rows of tensorA (index one inclusive index two exclusive): ')
print(tensorA[:2])
print('Slicing the first two columns of tensorA (take all rows, then slice columns): ')
print(tensorA[:,:2])

Slicing the first two rows of tensorA (index one inclusive index two exclusive): 
tensor([[1, 1, 1],
        [2, 2, 2]])
Slicing the first two columns of tensorA (take all rows, then slice columns): 
tensor([[1, 1],
        [2, 2]])


*Concatenation*

In [10]:
print('Vertically concatenate tensorA and tensorB: (default: dim=0)')
concat_v = torch.cat([tensorA, tensorB])
print(concat_v)

Vertically concatenate tensorA and tensorB: (default: dim=0)
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])


In [11]:
print('Horizontally concatenate tensorA and tensorB: (dim=1)')
concat_h = torch.cat([tensorA, tensorB], dim=1)
print(concat_h)

Horizontally concatenate tensorA and tensorB: (dim=1)
tensor([[1, 1, 1, 3, 3, 3],
        [2, 2, 2, 4, 4, 4]])
